#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Awning_02_512_01_IvansPizza

#include "Basic.hpp"

#include "BP_Master_Cloth_fixture_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Awning_02_512_01_IvansPizza.BP_Awning_02_512_01_IvansPizza_C
// 0x0000 (0x0338 - 0x0338)
class ABP_Awning_02_512_01_IvansPizza_C final : public ABP_Master_Cloth_Fixture_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Awning_02_512_01_IvansPizza_C">();
	}
	static class ABP_Awning_02_512_01_IvansPizza_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Awning_02_512_01_IvansPizza_C>();
	}
};
static_assert(alignof(ABP_Awning_02_512_01_IvansPizza_C) == 0x000008, "Wrong alignment on ABP_Awning_02_512_01_IvansPizza_C");
static_assert(sizeof(ABP_Awning_02_512_01_IvansPizza_C) == 0x000338, "Wrong size on ABP_Awning_02_512_01_IvansPizza_C");

}

