#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BackItemBagThermite

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BackItemBagThermite.BP_BackItemBagThermite_C
// 0x0008 (0x0308 - 0x0300)
class ABP_BackItemBagThermite_C final : public ASBZCarriedBag
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0300(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_BackItemBagThermite(int32 EntryPoint);
	void BP_AttachmentComplete(class USkeletalMeshComponent* ParentSkeletalMeshComponent);
	void BP_AdjustAttachment(int32 Index_0, int32 NewCount, const struct FTransform& NewStrapTransformOffset);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_BackItemBagThermite_C">();
	}
	static class ABP_BackItemBagThermite_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BackItemBagThermite_C>();
	}
};
static_assert(alignof(ABP_BackItemBagThermite_C) == 0x000008, "Wrong alignment on ABP_BackItemBagThermite_C");
static_assert(sizeof(ABP_BackItemBagThermite_C) == 0x000308, "Wrong size on ABP_BackItemBagThermite_C");
static_assert(offsetof(ABP_BackItemBagThermite_C, UberGraphFrame) == 0x000300, "Member 'ABP_BackItemBagThermite_C::UberGraphFrame' has a wrong offset!");

}

