#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CosmeticPickupPlank

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CosmeticPickupPlank.BP_CosmeticPickupPlank_C
// 0x0008 (0x02D0 - 0x02C8)
class ABP_CosmeticPickupPlank_C final : public ASBZCosmeticProp
{
public:
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CosmeticPickupPlank_C">();
	}
	static class ABP_CosmeticPickupPlank_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CosmeticPickupPlank_C>();
	}
};
static_assert(alignof(ABP_CosmeticPickupPlank_C) == 0x000008, "Wrong alignment on ABP_CosmeticPickupPlank_C");
static_assert(sizeof(ABP_CosmeticPickupPlank_C) == 0x0002D0, "Wrong size on ABP_CosmeticPickupPlank_C");
static_assert(offsetof(ABP_CosmeticPickupPlank_C, StaticMesh) == 0x0002C8, "Member 'ABP_CosmeticPickupPlank_C::StaticMesh' has a wrong offset!");

}

