#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CosmeticPlank

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CosmeticPlank.BP_CosmeticPlank_C
// 0x0008 (0x02D0 - 0x02C8)
class ABP_CosmeticPlank_C final : public ASBZCosmeticProp
{
public:
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CosmeticPlank_C">();
	}
	static class ABP_CosmeticPlank_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CosmeticPlank_C>();
	}
};
static_assert(alignof(ABP_CosmeticPlank_C) == 0x000008, "Wrong alignment on ABP_CosmeticPlank_C");
static_assert(sizeof(ABP_CosmeticPlank_C) == 0x0002D0, "Wrong size on ABP_CosmeticPlank_C");
static_assert(offsetof(ABP_CosmeticPlank_C, StaticMesh) == 0x0002C8, "Member 'ABP_CosmeticPlank_C::StaticMesh' has a wrong offset!");

}

