#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CosmeticZiptie

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CosmeticZiptie.BP_CosmeticZiptie_C
// 0x0008 (0x02D0 - 0x02C8)
class ABP_CosmeticZiptie_C final : public ASBZCosmeticProp
{
public:
	class USkeletalMeshComponent*                 SkeletalMesh;                                      // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CosmeticZiptie_C">();
	}
	static class ABP_CosmeticZiptie_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CosmeticZiptie_C>();
	}
};
static_assert(alignof(ABP_CosmeticZiptie_C) == 0x000008, "Wrong alignment on ABP_CosmeticZiptie_C");
static_assert(sizeof(ABP_CosmeticZiptie_C) == 0x0002D0, "Wrong size on ABP_CosmeticZiptie_C");
static_assert(offsetof(ABP_CosmeticZiptie_C, SkeletalMesh) == 0x0002C8, "Member 'ABP_CosmeticZiptie_C::SkeletalMesh' has a wrong offset!");

}

