#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DAT_SignStreet_01_6thAV

#include "Basic.hpp"

#include "BP_Tintable_Fixture_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DAT_SignStreet_01_6thAV.BP_DAT_SignStreet_01_6thAV_C
// 0x0000 (0x02E0 - 0x02E0)
class ABP_DAT_SignStreet_01_6thAV_C final : public ABP_Tintable_Fixture_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_DAT_SignStreet_01_6thAV_C">();
	}
	static class ABP_DAT_SignStreet_01_6thAV_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DAT_SignStreet_01_6thAV_C>();
	}
};
static_assert(alignof(ABP_DAT_SignStreet_01_6thAV_C) == 0x000008, "Wrong alignment on ABP_DAT_SignStreet_01_6thAV_C");
static_assert(sizeof(ABP_DAT_SignStreet_01_6thAV_C) == 0x0002E0, "Wrong size on ABP_DAT_SignStreet_01_6thAV_C");

}

