#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_InstantLoot_Money_02

#include "Basic.hpp"

#include "BP_InstantLoot_MoneyBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_InstantLoot_Money_02.BP_InstantLoot_Money_02_C
// 0x0008 (0x02F0 - 0x02E8)
class ABP_InstantLoot_Money_02_C final : public ABP_InstantLoot_MoneyBase_C
{
public:
	bool                                          Enable_Offset;                                     // 0x02E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void UserConstructionScript();
	void RandomOffset(bool EnableOffset);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_InstantLoot_Money_02_C">();
	}
	static class ABP_InstantLoot_Money_02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_InstantLoot_Money_02_C>();
	}
};
static_assert(alignof(ABP_InstantLoot_Money_02_C) == 0x000008, "Wrong alignment on ABP_InstantLoot_Money_02_C");
static_assert(sizeof(ABP_InstantLoot_Money_02_C) == 0x0002F0, "Wrong size on ABP_InstantLoot_Money_02_C");
static_assert(offsetof(ABP_InstantLoot_Money_02_C, Enable_Offset) == 0x0002E8, "Member 'ABP_InstantLoot_Money_02_C::Enable_Offset' has a wrong offset!");

}

