#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_InstantLoot_BraceletBox

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_InstantLoot_BraceletBox.BP_InstantLoot_BraceletBox_C
// 0x0010 (0x02F0 - 0x02E0)
class ABP_InstantLoot_BraceletBox_C final : public ASBZInstantLoot
{
public:
	class USBZAIObjectiveComponent*               SBZAIObjective;                                    // 0x02E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Loot;                                              // 0x02E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_InstantLoot_BraceletBox_C">();
	}
	static class ABP_InstantLoot_BraceletBox_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_InstantLoot_BraceletBox_C>();
	}
};
static_assert(alignof(ABP_InstantLoot_BraceletBox_C) == 0x000008, "Wrong alignment on ABP_InstantLoot_BraceletBox_C");
static_assert(sizeof(ABP_InstantLoot_BraceletBox_C) == 0x0002F0, "Wrong size on ABP_InstantLoot_BraceletBox_C");
static_assert(offsetof(ABP_InstantLoot_BraceletBox_C, SBZAIObjective) == 0x0002E0, "Member 'ABP_InstantLoot_BraceletBox_C::SBZAIObjective' has a wrong offset!");
static_assert(offsetof(ABP_InstantLoot_BraceletBox_C, Loot) == 0x0002E8, "Member 'ABP_InstantLoot_BraceletBox_C::Loot' has a wrong offset!");

}

