#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_InteractableUnBreachableDoubleDoor

#include "Basic.hpp"

#include "BP_InteractableUnBreachableDoubleDoor_classes.hpp"
#include "BP_InteractableUnBreachableDoubleDoor_parameters.hpp"


namespace SDK
{

// Function BP_InteractableUnBreachableDoubleDoor.BP_InteractableUnBreachableDoubleDoor_C.ExecuteUbergraph_BP_InteractableUnBreachableDoubleDoor
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_InteractableUnBreachableDoubleDoor_C::ExecuteUbergraph_BP_InteractableUnBreachableDoubleDoor(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractableUnBreachableDoubleDoor_C", "ExecuteUbergraph_BP_InteractableUnBreachableDoubleDoor");

	Params::BP_InteractableUnBreachableDoubleDoor_C_ExecuteUbergraph_BP_InteractableUnBreachableDoubleDoor Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_InteractableUnBreachableDoubleDoor.BP_InteractableUnBreachableDoubleDoor_C.onOpenAnimStarted
// (BlueprintCallable, BlueprintEvent)

void ABP_InteractableUnBreachableDoubleDoor_C::OnOpenAnimStarted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractableUnBreachableDoubleDoor_C", "onOpenAnimStarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_InteractableUnBreachableDoubleDoor.BP_InteractableUnBreachableDoubleDoor_C.onOpenAnimUpdateTick
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ESBZGateState                           OldState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ESBZGateState                           NewState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Alpha                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_InteractableUnBreachableDoubleDoor_C::OnOpenAnimUpdateTick(ESBZGateState OldState, ESBZGateState NewState, float Alpha)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractableUnBreachableDoubleDoor_C", "onOpenAnimUpdateTick");

	Params::BP_InteractableUnBreachableDoubleDoor_C_OnOpenAnimUpdateTick Parms{};

	Parms.OldState = OldState;
	Parms.NewState = NewState;
	Parms.Alpha = Alpha;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_InteractableUnBreachableDoubleDoor.BP_InteractableUnBreachableDoubleDoor_C.onDoorBreached
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ESBZGateState                           OldState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ESBZGateState                           NewState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_InteractableUnBreachableDoubleDoor_C::OnDoorBreached(ESBZGateState OldState, ESBZGateState NewState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractableUnBreachableDoubleDoor_C", "onDoorBreached");

	Params::BP_InteractableUnBreachableDoubleDoor_C_OnDoorBreached Parms{};

	Parms.OldState = OldState;
	Parms.NewState = NewState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_InteractableUnBreachableDoubleDoor.BP_InteractableUnBreachableDoubleDoor_C.initToValidPosition
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ESBZGateState                           OldState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_InteractableUnBreachableDoubleDoor_C::InitToValidPosition(ESBZGateState OldState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractableUnBreachableDoubleDoor_C", "initToValidPosition");

	Params::BP_InteractableUnBreachableDoubleDoor_C_InitToValidPosition Parms{};

	Parms.OldState = OldState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_InteractableUnBreachableDoubleDoor.BP_InteractableUnBreachableDoubleDoor_C.setBreachedMeshVisibility
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    breached                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_InteractableUnBreachableDoubleDoor_C::SetBreachedMeshVisibility(bool breached)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractableUnBreachableDoubleDoor_C", "setBreachedMeshVisibility");

	Params::BP_InteractableUnBreachableDoubleDoor_C_SetBreachedMeshVisibility Parms{};

	Parms.breached = breached;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_InteractableUnBreachableDoubleDoor.BP_InteractableUnBreachableDoubleDoor_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_InteractableUnBreachableDoubleDoor_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractableUnBreachableDoubleDoor_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

