#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_InstantLoot_BoxJewelry_01_Rings_F

#include "Basic.hpp"

#include "BP_InstantLoot_Diamond_01_A_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_InstantLoot_BoxJewelry_01_Rings_F.BP_InstantLoot_BoxJewelry_01_Rings_F_C
// 0x0000 (0x02F8 - 0x02F8)
class ABP_InstantLoot_BoxJewelry_01_Rings_F_C final : public ABP_InstantLoot_Diamond_01_A_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_InstantLoot_BoxJewelry_01_Rings_F_C">();
	}
	static class ABP_InstantLoot_BoxJewelry_01_Rings_F_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_InstantLoot_BoxJewelry_01_Rings_F_C>();
	}
};
static_assert(alignof(ABP_InstantLoot_BoxJewelry_01_Rings_F_C) == 0x000008, "Wrong alignment on ABP_InstantLoot_BoxJewelry_01_Rings_F_C");
static_assert(sizeof(ABP_InstantLoot_BoxJewelry_01_Rings_F_C) == 0x0002F8, "Wrong size on ABP_InstantLoot_BoxJewelry_01_Rings_F_C");

}

