#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Level_AmmoPack

#include "Basic.hpp"

#include "BP_AmmoPack_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Level_AmmoPack.BP_Level_AmmoPack_C
// 0x0000 (0x0550 - 0x0550)
class ABP_Level_AmmoPack_C final : public ABP_AmmoPack_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Level_AmmoPack_C">();
	}
	static class ABP_Level_AmmoPack_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Level_AmmoPack_C>();
	}
};
static_assert(alignof(ABP_Level_AmmoPack_C) == 0x000010, "Wrong alignment on ABP_Level_AmmoPack_C");
static_assert(sizeof(ABP_Level_AmmoPack_C) == 0x000550, "Wrong size on ABP_Level_AmmoPack_C");

}

