#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LaserPoint

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_LaserPoint.BP_LaserPoint_C
// 0x0010 (0x05B0 - 0x05A0)
class UBP_LaserPoint_C final : public USBZLaserPoint
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x05A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_LaserPoint(int32 EntryPoint);
	void ReceiveActorBeginOverlap_1(class AActor* OtherActor);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_LaserPoint_C">();
	}
	static class UBP_LaserPoint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_LaserPoint_C>();
	}
};
static_assert(alignof(UBP_LaserPoint_C) == 0x000010, "Wrong alignment on UBP_LaserPoint_C");
static_assert(sizeof(UBP_LaserPoint_C) == 0x0005B0, "Wrong size on UBP_LaserPoint_C");
static_assert(offsetof(UBP_LaserPoint_C, UberGraphFrame) == 0x0005A0, "Member 'UBP_LaserPoint_C::UberGraphFrame' has a wrong offset!");

}

