#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MicroscopeJewelry_01

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MicroscopeJewelry_01.BP_MicroscopeJewelry_01_C
// 0x0000 (0x02D8 - 0x02D8)
class ABP_MicroscopeJewelry_01_C final : public ASBZSmallCosmeticDestruction
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MicroscopeJewelry_01_C">();
	}
	static class ABP_MicroscopeJewelry_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MicroscopeJewelry_01_C>();
	}
};
static_assert(alignof(ABP_MicroscopeJewelry_01_C) == 0x000008, "Wrong alignment on ABP_MicroscopeJewelry_01_C");
static_assert(sizeof(ABP_MicroscopeJewelry_01_C) == 0x0002D8, "Wrong size on ABP_MicroscopeJewelry_01_C");

}

