#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Suv_Base

#include "Basic.hpp"

#include "BP_WheeledVehicle_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Suv_Base.BP_Suv_Base_C
// 0x0000 (0x0710 - 0x0710)
class ABP_Suv_Base_C : public ABP_WheeledVehicle_Base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Suv_Base_C">();
	}
	static class ABP_Suv_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Suv_Base_C>();
	}
};
static_assert(alignof(ABP_Suv_Base_C) == 0x000010, "Wrong alignment on ABP_Suv_Base_C");
static_assert(sizeof(ABP_Suv_Base_C) == 0x000710, "Wrong size on ABP_Suv_Base_C");

}

