#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WindowCleaningCradle

#include "Basic.hpp"

#include "BP_WindowCleaningCradle_classes.hpp"
#include "BP_WindowCleaningCradle_parameters.hpp"


namespace SDK
{

// Function BP_WindowCleaningCradle.BP_WindowCleaningCradle_C.OnCradleLowered__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void ABP_WindowCleaningCradle_C::OnCradleLowered__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_WindowCleaningCradle_C", "OnCradleLowered__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_WindowCleaningCradle.BP_WindowCleaningCradle_C.ExecuteUbergraph_BP_WindowCleaningCradle
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_WindowCleaningCradle_C::ExecuteUbergraph_BP_WindowCleaningCradle(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_WindowCleaningCradle_C", "ExecuteUbergraph_BP_WindowCleaningCradle");

	Params::BP_WindowCleaningCradle_C_ExecuteUbergraph_BP_WindowCleaningCradle Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_WindowCleaningCradle.BP_WindowCleaningCradle_C.BndEvt__BP_EscapeVan_SBZSecuredBagVisualize_K2Node_ComponentBoundEvent_0_SBZSecuredBagVisualizeBagAddedSignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class USBZBagType*                      BagType                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_WindowCleaningCradle_C::BndEvt__BP_EscapeVan_SBZSecuredBagVisualize_K2Node_ComponentBoundEvent_0_SBZSecuredBagVisualizeBagAddedSignature__DelegateSignature(const class USBZBagType* BagType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_WindowCleaningCradle_C", "BndEvt__BP_EscapeVan_SBZSecuredBagVisualize_K2Node_ComponentBoundEvent_0_SBZSecuredBagVisualizeBagAddedSignature__DelegateSignature");

	Params::BP_WindowCleaningCradle_C_BndEvt__BP_EscapeVan_SBZSecuredBagVisualize_K2Node_ComponentBoundEvent_0_SBZSecuredBagVisualizeBagAddedSignature__DelegateSignature Parms{};

	Parms.BagType = BagType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_WindowCleaningCradle.BP_WindowCleaningCradle_C.BP_OnStateChanged
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)
// Parameters:
// ESBZTimerState                          NewState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ESBZTimerState                          OldState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bDoCosmetics                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_WindowCleaningCradle_C::BP_OnStateChanged(ESBZTimerState NewState, ESBZTimerState OldState, bool bDoCosmetics)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_WindowCleaningCradle_C", "BP_OnStateChanged");

	Params::BP_WindowCleaningCradle_C_BP_OnStateChanged Parms{};

	Parms.NewState = NewState;
	Parms.OldState = OldState;
	Parms.bDoCosmetics = bDoCosmetics;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_WindowCleaningCradle.BP_WindowCleaningCradle_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_WindowCleaningCradle_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_WindowCleaningCradle_C", "ReceiveTick");

	Params::BP_WindowCleaningCradle_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_WindowCleaningCradle.BP_WindowCleaningCradle_C.SetPlatformLocation
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_WindowCleaningCradle_C::SetPlatformLocation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_WindowCleaningCradle_C", "SetPlatformLocation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_WindowCleaningCradle.BP_WindowCleaningCradle_C.ShowMarker
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_WindowCleaningCradle_C::ShowMarker()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_WindowCleaningCradle_C", "ShowMarker");

	UObject::ProcessEvent(Func, nullptr);
}

}

