#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CH_Civilian_Employee_Female_Suit

#include "Basic.hpp"

#include "CH_BaseEmployeeCivilian_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CH_Civilian_Employee_Female_Suit.CH_Civilian_Employee_Female_Suit_C
// 0x0000 (0x1C80 - 0x1C80)
class ACH_Civilian_Employee_Female_Suit_C final : public ACH_BaseEmployeeCivilian_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CH_Civilian_Employee_Female_Suit_C">();
	}
	static class ACH_Civilian_Employee_Female_Suit_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACH_Civilian_Employee_Female_Suit_C>();
	}
};
static_assert(alignof(ACH_Civilian_Employee_Female_Suit_C) == 0x000010, "Wrong alignment on ACH_Civilian_Employee_Female_Suit_C");
static_assert(sizeof(ACH_Civilian_Employee_Female_Suit_C) == 0x001C80, "Wrong size on ACH_Civilian_Employee_Female_Suit_C");

}

