#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: G_DiamondDistrict_AI

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass G_DiamondDistrict_AI.G_DiamondDistrict_AI_C
// 0x0008 (0x0348 - 0x0340)
class AG_DiamondDistrict_AI_C final : public ASBZLevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0340(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_G_DiamondDistrict_AI(int32 EntryPoint);
	void BndEvt__G_DiamondDistrict_AI_SBZTrafficSpline_FirstResponders2_K2Node_ActorBoundEvent_1_SBZSplineOnEnter__DelegateSignature(class ASBZSpline* Spline, class AActor* Actor);
	void BndEvt__G_DiamondDistrict_AI_SBZTrafficSpline_FirstResponders1_K2Node_ActorBoundEvent_0_SBZSplineOnEnter__DelegateSignature(class ASBZSpline* Spline, class AActor* Actor);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"G_DiamondDistrict_AI_C">();
	}
	static class AG_DiamondDistrict_AI_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AG_DiamondDistrict_AI_C>();
	}
};
static_assert(alignof(AG_DiamondDistrict_AI_C) == 0x000008, "Wrong alignment on AG_DiamondDistrict_AI_C");
static_assert(sizeof(AG_DiamondDistrict_AI_C) == 0x000348, "Wrong size on AG_DiamondDistrict_AI_C");
static_assert(offsetof(AG_DiamondDistrict_AI_C, UberGraphFrame) == 0x000340, "Member 'AG_DiamondDistrict_AI_C::UberGraphFrame' has a wrong offset!");

}

