#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_HET5_AOE

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_HET5_AOE.GE_HET5_AOE_C
// 0x0000 (0x08C0 - 0x08C0)
class UGE_HET5_AOE_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_HET5_AOE_C">();
	}
	static class UGE_HET5_AOE_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_HET5_AOE_C>();
	}
};
static_assert(alignof(UGE_HET5_AOE_C) == 0x000008, "Wrong alignment on UGE_HET5_AOE_C");
static_assert(sizeof(UGE_HET5_AOE_C) == 0x0008C0, "Wrong size on UGE_HET5_AOE_C");

}

