#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Traffic_light_switcher

#include "Basic.hpp"

#include "Traffic_light_switcher_classes.hpp"
#include "Traffic_light_switcher_parameters.hpp"


namespace SDK
{

// Function Traffic_light_switcher.Traffic_light_switcher_C.ExecuteUbergraph_Traffic_light_switcher
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATraffic_light_switcher_C::ExecuteUbergraph_Traffic_light_switcher(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Traffic_light_switcher_C", "ExecuteUbergraph_Traffic_light_switcher");

	Params::Traffic_light_switcher_C_ExecuteUbergraph_Traffic_light_switcher Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Traffic_light_switcher.Traffic_light_switcher_C.refresh_traffic_light_status
// (BlueprintCallable, BlueprintEvent)

void ATraffic_light_switcher_C::Refresh_traffic_light_status()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Traffic_light_switcher_C", "refresh_traffic_light_status");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Traffic_light_switcher.Traffic_light_switcher_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATraffic_light_switcher_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Traffic_light_switcher_C", "ReceiveTick");

	Params::Traffic_light_switcher_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Traffic_light_switcher.Traffic_light_switcher_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ATraffic_light_switcher_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Traffic_light_switcher_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Traffic_light_switcher.Traffic_light_switcher_C.update_pool
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class AActor*>                   Pool                                                   (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// ETraffic_light_status                   Status                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATraffic_light_switcher_C::Update_pool(TArray<class AActor*>& Pool, ETraffic_light_status Status)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Traffic_light_switcher_C", "update_pool");

	Params::Traffic_light_switcher_C_Update_pool Parms{};

	Parms.Pool = std::move(Pool);
	Parms.Status = Status;

	UObject::ProcessEvent(Func, &Parms);

	Pool = std::move(Parms.Pool);
}

}

