#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_Blackmarket_Inspect

#include "Basic.hpp"

#include "Starbreeze_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function WBP_UI_Blackmarket_Inspect.WBP_UI_Blackmarket_Inspect_C.ExecuteUbergraph_WBP_UI_Blackmarket_Inspect
// 0x0C30 (0x0C30 - 0x0000)
struct WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZMaskPartConfigGroup                K2Node_MakeStruct_SBZMaskPartConfigGroup;          // 0x0008(0x0010)(NoDestructor)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSBZButtonControlsReference            K2Node_MakeStruct_SBZButtonControlsReference;      // 0x0020(0x0028)()
	struct FSBZButtonControlReference             K2Node_MakeStruct_SBZButtonControlReference;       // 0x0048(0x0030)()
	bool                                          CallFunc_IsInputTypeController_ReturnValue;        // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_79[0x3];                                       // 0x0079(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSBZButtonControlReference             K2Node_MakeStruct_SBZButtonControlReference_1;     // 0x0080(0x0030)()
	struct FSBZButtonControlReference             K2Node_MakeStruct_SBZButtonControlReference_2;     // 0x00B0(0x0030)()
	struct FSBZButtonControlReference             K2Node_MakeStruct_SBZButtonControlReference_3;     // 0x00E0(0x0030)()
	TDelegate<void(class FName ActionName)>       K2Node_CreateDelegate_OutputDelegate;              // 0x0110(0x0014)(ZeroConstructor, NoDestructor)
	int32                                         CallFunc_Array_Add_ReturnValue_1;                  // 0x0124(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_2;                  // 0x0128(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_3;                  // 0x012C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName ActionName)>       K2Node_CreateDelegate_OutputDelegate_1;            // 0x0130(0x0014)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_144[0x4];                                      // 0x0144(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZButtonControlsReference            K2Node_MakeStruct_SBZButtonControlsReference_1;    // 0x0148(0x0028)()
	class FName                                   K2Node_Event_PreviousValue;                        // 0x0170(0x000C)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_ActionName;                     // 0x017C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZCustomizationManager*               CallFunc_GetCustomizationManager_ReturnValue;      // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchName_CmpSuccess;                      // 0x0190(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_191[0x7];                                      // 0x0191(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USBZUIManager*                          CallFunc_GetUIManager_ReturnValue;                 // 0x0198(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_PopStack_ReturnValue;                     // 0x01A0(0x000C)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1AC[0x4];                                      // 0x01AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USBZBaseWeaponData*                     K2Node_DynamicCast_AsSBZBase_Weapon_Data;          // 0x01B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x01B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1B9[0x7];                                      // 0x01B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZButtonControlReference             K2Node_MakeStruct_SBZButtonControlReference_4;     // 0x01C0(0x0030)()
	struct FSBZButtonControlReference             K2Node_MakeStruct_SBZButtonControlReference_5;     // 0x01F0(0x0030)()
	int32                                         CallFunc_Array_Add_ReturnValue_4;                  // 0x0220(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_5;                  // 0x0224(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSBZButtonControlReference             K2Node_MakeStruct_SBZButtonControlReference_6;     // 0x0228(0x0030)()
	int32                                         CallFunc_Array_Add_ReturnValue_6;                  // 0x0258(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_25C[0x4];                                      // 0x025C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USBZMaskData*                           K2Node_DynamicCast_AsSBZMask_Data;                 // 0x0260(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0268(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_269[0x7];                                      // 0x0269(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ASBZCustomizationManager*               CallFunc_GetCustomizationManager_ReturnValue_1;    // 0x0270(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSBZMaskConfig                         K2Node_MakeStruct_SBZMaskConfig;                   // 0x0278(0x0070)()
	bool                                          CallFunc_IsInputTypeController_ReturnValue_1;      // 0x02E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2E9[0x7];                                      // 0x02E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	const class USBZMaskMouldData*                K2Node_DynamicCast_AsSBZMask_Mould_Data;           // 0x02F0(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x02F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2F9[0x7];                                      // 0x02F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZMaskPartConfigGroup                K2Node_MakeStruct_SBZMaskPartConfigGroup_1;        // 0x0300(0x0010)(NoDestructor)
	TMap<class USBZModularPartSlotBase*, struct FSBZMaskPartConfigGroup> K2Node_MakeMap_Map;                                // 0x0310(0x0050)()
	const class USBZMaskVFXData*                  K2Node_DynamicCast_AsSBZMask_VFXData;              // 0x0360(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0368(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_369[0x7];                                      // 0x0369(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZMaskConfig                         K2Node_MakeStruct_SBZMaskConfig_1;                 // 0x0370(0x0070)()
	struct FSBZMaskPartConfigGroup                K2Node_MakeStruct_SBZMaskPartConfigGroup_2;        // 0x03E0(0x0010)(NoDestructor)
	TMap<class USBZModularPartSlotBase*, struct FSBZMaskPartConfigGroup> K2Node_MakeMap_Map_1;                              // 0x03F0(0x0050)()
	const class USBZMaskMaterialData*             K2Node_DynamicCast_AsSBZMask_Material_Data;        // 0x0440(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x0448(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_449[0x7];                                      // 0x0449(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZMaskConfig                         K2Node_MakeStruct_SBZMaskConfig_2;                 // 0x0450(0x0070)()
	struct FSBZMaskPartConfigGroup                K2Node_MakeStruct_SBZMaskPartConfigGroup_3;        // 0x04C0(0x0010)(NoDestructor)
	TMap<class USBZModularPartSlotBase*, struct FSBZMaskPartConfigGroup> K2Node_MakeMap_Map_2;                              // 0x04D0(0x0050)()
	const class USBZMaskPatternData*              K2Node_DynamicCast_AsSBZMask_Pattern_Data;         // 0x0520(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_5;                     // 0x0528(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_529[0x7];                                      // 0x0529(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZMaskConfig                         K2Node_MakeStruct_SBZMaskConfig_3;                 // 0x0530(0x0070)()
	struct FSBZMaskPartConfigGroup                K2Node_MakeStruct_SBZMaskPartConfigGroup_4;        // 0x05A0(0x0010)(NoDestructor)
	struct FSBZMaskPartConfigGroup                K2Node_MakeStruct_SBZMaskPartConfigGroup_5;        // 0x05B0(0x0010)(NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x05C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5C1[0x7];                                      // 0x05C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ASBZMainMenuCameraManager*              CallFunc_GetMainMenuCameraManager_ReturnValue;     // 0x05C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSBZButtonControlReference             K2Node_MakeStruct_SBZButtonControlReference_7;     // 0x05D0(0x0030)()
	const class USBZWeaponCharmData*              K2Node_DynamicCast_AsSBZWeapon_Charm_Data;         // 0x0600(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_6;                     // 0x0608(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_609[0x3];                                      // 0x0609(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_MakeLiteralName_ReturnValue;              // 0x060C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSBZEquippablePartConfigGroup          K2Node_MakeStruct_SBZEquippablePartConfigGroup;    // 0x0618(0x0010)(NoDestructor)
	TMap<class USBZModularPartSlotBase*, struct FSBZEquippablePartConfigGroup> K2Node_MakeMap_Map_3;                              // 0x0628(0x0050)()
	class ASBZCustomizationManager*               CallFunc_GetCustomizationManager_ReturnValue_2;    // 0x0678(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSBZEquippableConfig                   K2Node_MakeStruct_SBZEquippableConfig;             // 0x0680(0x0070)()
	int32                                         CallFunc_Array_Add_ReturnValue_7;                  // 0x06F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6F4[0x4];                                      // 0x06F4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZMaskPartConfigGroup                K2Node_MakeStruct_SBZMaskPartConfigGroup_6;        // 0x06F8(0x0010)(NoDestructor)
	TMap<class USBZModularPartSlotBase*, struct FSBZMaskPartConfigGroup> K2Node_MakeMap_Map_4;                              // 0x0708(0x0050)()
	struct FSBZButtonControlsReference            K2Node_MakeStruct_SBZButtonControlsReference_2;    // 0x0758(0x0028)()
	struct FSBZMaskConfig                         K2Node_MakeStruct_SBZMaskConfig_4;                 // 0x0780(0x0070)()
	TDelegate<void(class FName ActionName)>       K2Node_CreateDelegate_OutputDelegate_2;            // 0x07F0(0x0014)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_804[0x4];                                      // 0x0804(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZMaskPartConfigGroup                K2Node_MakeStruct_SBZMaskPartConfigGroup_7;        // 0x0808(0x0010)(NoDestructor)
	struct FSBZMaskPartConfigGroup                K2Node_MakeStruct_SBZMaskPartConfigGroup_8;        // 0x0818(0x0010)(NoDestructor)
	struct FSBZMaskPartConfigGroup                K2Node_MakeStruct_SBZMaskPartConfigGroup_9;        // 0x0828(0x0010)(NoDestructor)
	struct FSBZMaskPartConfigGroup                K2Node_MakeStruct_SBZMaskPartConfigGroup_10;       // 0x0838(0x0010)(NoDestructor)
	struct FSBZButtonControlReference             K2Node_MakeStruct_SBZButtonControlReference_8;     // 0x0848(0x0030)()
	TMap<class USBZModularPartSlotBase*, struct FSBZMaskPartConfigGroup> K2Node_MakeMap_Map_5;                              // 0x0878(0x0050)()
	int32                                         CallFunc_Array_Add_ReturnValue_8;                  // 0x08C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8CC[0x4];                                      // 0x08CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZMaskConfig                         K2Node_MakeStruct_SBZMaskConfig_5;                 // 0x08D0(0x0070)()
	struct FSBZButtonControlReference             K2Node_MakeStruct_SBZButtonControlReference_9;     // 0x0940(0x0030)()
	int32                                         CallFunc_Array_Add_ReturnValue_9;                  // 0x0970(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_974[0x4];                                      // 0x0974(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZButtonControlReference             K2Node_MakeStruct_SBZButtonControlReference_10;    // 0x0978(0x0030)()
	class ASBZMainMenuCameraManager*              CallFunc_GetMainMenuCameraManager_ReturnValue_1;   // 0x09A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_10;                 // 0x09B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsInputTypeController_ReturnValue_2;      // 0x09B4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9B5[0x3];                                      // 0x09B5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZButtonControlReference             K2Node_MakeStruct_SBZButtonControlReference_11;    // 0x09B8(0x0030)()
	class FName                                   CallFunc_MakeLiteralName_ReturnValue_1;            // 0x09E8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_11;                 // 0x09F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGameModeBase*                          CallFunc_GetGameMode_ReturnValue;                  // 0x09F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZGameModeMainMenu*                   K2Node_DynamicCast_AsSBZGame_Mode_Main_Menu;       // 0x0A00(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_7;                     // 0x0A08(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0A09(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0A0A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0A0B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A0C[0x4];                                      // 0x0A0C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ASBZCustomizationManager*               CallFunc_GetCustomizationManager_ReturnValue_3;    // 0x0A10(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZWeaponPresetConfigData*             K2Node_DynamicCast_AsSBZWeapon_Preset_Config_Data; // 0x0A18(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_8;                     // 0x0A20(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A21[0x7];                                      // 0x0A21(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZEquippableConfig                   CallFunc_GetEquippableConfig_ReturnValue;          // 0x0A28(0x0070)(ConstParm)
	class ASBZCustomizationManager*               CallFunc_GetCustomizationManager_ReturnValue_4;    // 0x0A98(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZCustomizationManager*               CallFunc_GetCustomizationManager_ReturnValue_5;    // 0x0AA0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class USBZMaskPreconfigData*            K2Node_DynamicCast_AsSBZMask_Preconfig_Data;       // 0x0AA8(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_9;                     // 0x0AB0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_AB1[0x7];                                      // 0x0AB1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZMaskConfig                         CallFunc_GetMaskConfig_ReturnValue;                // 0x0AB8(0x0070)(ConstParm)
	class FName                                   CallFunc_MakeLiteralName_ReturnValue_2;            // 0x0B28(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B34[0x4];                                      // 0x0B34(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZMaskConfig                         K2Node_MakeStruct_SBZMaskConfig_6;                 // 0x0B38(0x0070)()
	struct FSBZSuitConfig                         CallFunc_GetPreviewSuitConfig_ReturnValue;         // 0x0BA8(0x0028)(ConstParm)
	const class USBZSuitBaseData*                 K2Node_DynamicCast_AsSBZSuit_Base_Data;            // 0x0BD0(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_10;                    // 0x0BD8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_BD9[0x7];                                      // 0x0BD9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZSuitConfig                         K2Node_MakeStruct_SBZSuitConfig;                   // 0x0BE0(0x0028)()
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0C08(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0C09(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0C0A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C0B[0x5];                                      // 0x0C0B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class USBZGloveData*                          K2Node_DynamicCast_AsSBZGlove_Data;                // 0x0C10(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_11;                    // 0x0C18(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C19[0x7];                                      // 0x0C19(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ASBZMainMenuCameraManager*              CallFunc_GetMainMenuCameraManager_ReturnValue_2;   // 0x0C20(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsLoading;                           // 0x0C28(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0C29(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect) == 0x000008, "Wrong alignment on WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect");
static_assert(sizeof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect) == 0x000C30, "Wrong size on WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, EntryPoint) == 0x000000, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZMaskPartConfigGroup) == 0x000008, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZMaskPartConfigGroup' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_PlayAnimation_ReturnValue) == 0x000018, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZButtonControlsReference) == 0x000020, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZButtonControlsReference' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZButtonControlReference) == 0x000048, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZButtonControlReference' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_IsInputTypeController_ReturnValue) == 0x000078, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_IsInputTypeController_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_Array_Add_ReturnValue) == 0x00007C, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZButtonControlReference_1) == 0x000080, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZButtonControlReference_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZButtonControlReference_2) == 0x0000B0, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZButtonControlReference_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZButtonControlReference_3) == 0x0000E0, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZButtonControlReference_3' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_CreateDelegate_OutputDelegate) == 0x000110, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_Array_Add_ReturnValue_1) == 0x000124, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_Array_Add_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_Array_Add_ReturnValue_2) == 0x000128, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_Array_Add_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_Array_Add_ReturnValue_3) == 0x00012C, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_Array_Add_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_CreateDelegate_OutputDelegate_1) == 0x000130, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZButtonControlsReference_1) == 0x000148, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZButtonControlsReference_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_Event_PreviousValue) == 0x000170, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_Event_PreviousValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_CustomEvent_ActionName) == 0x00017C, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_CustomEvent_ActionName' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_GetCustomizationManager_ReturnValue) == 0x000188, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_GetCustomizationManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_SwitchName_CmpSuccess) == 0x000190, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_SwitchName_CmpSuccess' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_GetUIManager_ReturnValue) == 0x000198, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_GetUIManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_PopStack_ReturnValue) == 0x0001A0, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_PopStack_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_DynamicCast_AsSBZBase_Weapon_Data) == 0x0001B0, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_DynamicCast_AsSBZBase_Weapon_Data' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_DynamicCast_bSuccess) == 0x0001B8, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZButtonControlReference_4) == 0x0001C0, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZButtonControlReference_4' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZButtonControlReference_5) == 0x0001F0, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZButtonControlReference_5' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_Array_Add_ReturnValue_4) == 0x000220, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_Array_Add_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_Array_Add_ReturnValue_5) == 0x000224, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_Array_Add_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZButtonControlReference_6) == 0x000228, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZButtonControlReference_6' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_Array_Add_ReturnValue_6) == 0x000258, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_Array_Add_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_DynamicCast_AsSBZMask_Data) == 0x000260, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_DynamicCast_AsSBZMask_Data' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_DynamicCast_bSuccess_1) == 0x000268, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_GetCustomizationManager_ReturnValue_1) == 0x000270, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_GetCustomizationManager_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZMaskConfig) == 0x000278, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZMaskConfig' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_IsInputTypeController_ReturnValue_1) == 0x0002E8, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_IsInputTypeController_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_DynamicCast_AsSBZMask_Mould_Data) == 0x0002F0, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_DynamicCast_AsSBZMask_Mould_Data' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_DynamicCast_bSuccess_2) == 0x0002F8, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZMaskPartConfigGroup_1) == 0x000300, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZMaskPartConfigGroup_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeMap_Map) == 0x000310, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeMap_Map' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_DynamicCast_AsSBZMask_VFXData) == 0x000360, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_DynamicCast_AsSBZMask_VFXData' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_DynamicCast_bSuccess_3) == 0x000368, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZMaskConfig_1) == 0x000370, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZMaskConfig_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZMaskPartConfigGroup_2) == 0x0003E0, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZMaskPartConfigGroup_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeMap_Map_1) == 0x0003F0, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeMap_Map_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_DynamicCast_AsSBZMask_Material_Data) == 0x000440, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_DynamicCast_AsSBZMask_Material_Data' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_DynamicCast_bSuccess_4) == 0x000448, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZMaskConfig_2) == 0x000450, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZMaskConfig_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZMaskPartConfigGroup_3) == 0x0004C0, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZMaskPartConfigGroup_3' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeMap_Map_2) == 0x0004D0, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeMap_Map_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_DynamicCast_AsSBZMask_Pattern_Data) == 0x000520, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_DynamicCast_AsSBZMask_Pattern_Data' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_DynamicCast_bSuccess_5) == 0x000528, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_DynamicCast_bSuccess_5' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZMaskConfig_3) == 0x000530, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZMaskConfig_3' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZMaskPartConfigGroup_4) == 0x0005A0, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZMaskPartConfigGroup_4' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZMaskPartConfigGroup_5) == 0x0005B0, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZMaskPartConfigGroup_5' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x0005C0, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_GetMainMenuCameraManager_ReturnValue) == 0x0005C8, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_GetMainMenuCameraManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZButtonControlReference_7) == 0x0005D0, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZButtonControlReference_7' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_DynamicCast_AsSBZWeapon_Charm_Data) == 0x000600, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_DynamicCast_AsSBZWeapon_Charm_Data' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_DynamicCast_bSuccess_6) == 0x000608, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_DynamicCast_bSuccess_6' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_MakeLiteralName_ReturnValue) == 0x00060C, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_MakeLiteralName_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZEquippablePartConfigGroup) == 0x000618, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZEquippablePartConfigGroup' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeMap_Map_3) == 0x000628, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeMap_Map_3' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_GetCustomizationManager_ReturnValue_2) == 0x000678, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_GetCustomizationManager_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZEquippableConfig) == 0x000680, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZEquippableConfig' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_Array_Add_ReturnValue_7) == 0x0006F0, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_Array_Add_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZMaskPartConfigGroup_6) == 0x0006F8, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZMaskPartConfigGroup_6' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeMap_Map_4) == 0x000708, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeMap_Map_4' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZButtonControlsReference_2) == 0x000758, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZButtonControlsReference_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZMaskConfig_4) == 0x000780, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZMaskConfig_4' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_CreateDelegate_OutputDelegate_2) == 0x0007F0, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZMaskPartConfigGroup_7) == 0x000808, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZMaskPartConfigGroup_7' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZMaskPartConfigGroup_8) == 0x000818, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZMaskPartConfigGroup_8' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZMaskPartConfigGroup_9) == 0x000828, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZMaskPartConfigGroup_9' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZMaskPartConfigGroup_10) == 0x000838, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZMaskPartConfigGroup_10' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZButtonControlReference_8) == 0x000848, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZButtonControlReference_8' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeMap_Map_5) == 0x000878, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeMap_Map_5' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_Array_Add_ReturnValue_8) == 0x0008C8, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_Array_Add_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZMaskConfig_5) == 0x0008D0, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZMaskConfig_5' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZButtonControlReference_9) == 0x000940, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZButtonControlReference_9' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_Array_Add_ReturnValue_9) == 0x000970, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_Array_Add_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZButtonControlReference_10) == 0x000978, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZButtonControlReference_10' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_GetMainMenuCameraManager_ReturnValue_1) == 0x0009A8, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_GetMainMenuCameraManager_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_Array_Add_ReturnValue_10) == 0x0009B0, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_Array_Add_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_IsInputTypeController_ReturnValue_2) == 0x0009B4, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_IsInputTypeController_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZButtonControlReference_11) == 0x0009B8, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZButtonControlReference_11' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_MakeLiteralName_ReturnValue_1) == 0x0009E8, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_MakeLiteralName_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_Array_Add_ReturnValue_11) == 0x0009F4, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_Array_Add_ReturnValue_11' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_GetGameMode_ReturnValue) == 0x0009F8, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_GetGameMode_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_DynamicCast_AsSBZGame_Mode_Main_Menu) == 0x000A00, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_DynamicCast_AsSBZGame_Mode_Main_Menu' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_DynamicCast_bSuccess_7) == 0x000A08, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_DynamicCast_bSuccess_7' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, Temp_byte_Variable) == 0x000A09, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, Temp_byte_Variable_1) == 0x000A0A, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, Temp_bool_Variable) == 0x000A0B, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_GetCustomizationManager_ReturnValue_3) == 0x000A10, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_GetCustomizationManager_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_DynamicCast_AsSBZWeapon_Preset_Config_Data) == 0x000A18, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_DynamicCast_AsSBZWeapon_Preset_Config_Data' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_DynamicCast_bSuccess_8) == 0x000A20, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_DynamicCast_bSuccess_8' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_GetEquippableConfig_ReturnValue) == 0x000A28, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_GetEquippableConfig_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_GetCustomizationManager_ReturnValue_4) == 0x000A98, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_GetCustomizationManager_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_GetCustomizationManager_ReturnValue_5) == 0x000AA0, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_GetCustomizationManager_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_DynamicCast_AsSBZMask_Preconfig_Data) == 0x000AA8, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_DynamicCast_AsSBZMask_Preconfig_Data' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_DynamicCast_bSuccess_9) == 0x000AB0, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_DynamicCast_bSuccess_9' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_GetMaskConfig_ReturnValue) == 0x000AB8, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_GetMaskConfig_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_MakeLiteralName_ReturnValue_2) == 0x000B28, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_MakeLiteralName_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZMaskConfig_6) == 0x000B38, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZMaskConfig_6' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_GetPreviewSuitConfig_ReturnValue) == 0x000BA8, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_GetPreviewSuitConfig_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_DynamicCast_AsSBZSuit_Base_Data) == 0x000BD0, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_DynamicCast_AsSBZSuit_Base_Data' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_DynamicCast_bSuccess_10) == 0x000BD8, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_DynamicCast_bSuccess_10' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_MakeStruct_SBZSuitConfig) == 0x000BE0, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_MakeStruct_SBZSuitConfig' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_IsValid_ReturnValue) == 0x000C08, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_IsValid_ReturnValue_1) == 0x000C09, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_BooleanOR_ReturnValue) == 0x000C0A, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_DynamicCast_AsSBZGlove_Data) == 0x000C10, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_DynamicCast_AsSBZGlove_Data' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_DynamicCast_bSuccess_11) == 0x000C18, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_DynamicCast_bSuccess_11' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, CallFunc_GetMainMenuCameraManager_ReturnValue_2) == 0x000C20, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::CallFunc_GetMainMenuCameraManager_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_Event_bIsLoading) == 0x000C28, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_Event_bIsLoading' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect, K2Node_Select_Default) == 0x000C29, "Member 'WBP_UI_Blackmarket_Inspect_C_ExecuteUbergraph_WBP_UI_Blackmarket_Inspect::K2Node_Select_Default' has a wrong offset!");

// Function WBP_UI_Blackmarket_Inspect.WBP_UI_Blackmarket_Inspect_C.OnCustomizationActorLoadingChanged
// 0x0001 (0x0001 - 0x0000)
struct WBP_UI_Blackmarket_Inspect_C_OnCustomizationActorLoadingChanged final
{
public:
	bool                                          bIsLoading;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_UI_Blackmarket_Inspect_C_OnCustomizationActorLoadingChanged) == 0x000001, "Wrong alignment on WBP_UI_Blackmarket_Inspect_C_OnCustomizationActorLoadingChanged");
static_assert(sizeof(WBP_UI_Blackmarket_Inspect_C_OnCustomizationActorLoadingChanged) == 0x000001, "Wrong size on WBP_UI_Blackmarket_Inspect_C_OnCustomizationActorLoadingChanged");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_OnCustomizationActorLoadingChanged, bIsLoading) == 0x000000, "Member 'WBP_UI_Blackmarket_Inspect_C_OnCustomizationActorLoadingChanged::bIsLoading' has a wrong offset!");

// Function WBP_UI_Blackmarket_Inspect.WBP_UI_Blackmarket_Inspect_C.OnControlReferenceClicked
// 0x000C (0x000C - 0x0000)
struct WBP_UI_Blackmarket_Inspect_C_OnControlReferenceClicked final
{
public:
	class FName                                   ActionName;                                        // 0x0000(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_UI_Blackmarket_Inspect_C_OnControlReferenceClicked) == 0x000004, "Wrong alignment on WBP_UI_Blackmarket_Inspect_C_OnControlReferenceClicked");
static_assert(sizeof(WBP_UI_Blackmarket_Inspect_C_OnControlReferenceClicked) == 0x00000C, "Wrong size on WBP_UI_Blackmarket_Inspect_C_OnControlReferenceClicked");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_OnControlReferenceClicked, ActionName) == 0x000000, "Member 'WBP_UI_Blackmarket_Inspect_C_OnControlReferenceClicked::ActionName' has a wrong offset!");

// Function WBP_UI_Blackmarket_Inspect.WBP_UI_Blackmarket_Inspect_C.OnGainedStackFocused
// 0x000C (0x000C - 0x0000)
struct WBP_UI_Blackmarket_Inspect_C_OnGainedStackFocused final
{
public:
	class FName                                   PreviousValue;                                     // 0x0000(0x000C)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_UI_Blackmarket_Inspect_C_OnGainedStackFocused) == 0x000004, "Wrong alignment on WBP_UI_Blackmarket_Inspect_C_OnGainedStackFocused");
static_assert(sizeof(WBP_UI_Blackmarket_Inspect_C_OnGainedStackFocused) == 0x00000C, "Wrong size on WBP_UI_Blackmarket_Inspect_C_OnGainedStackFocused");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_OnGainedStackFocused, PreviousValue) == 0x000000, "Member 'WBP_UI_Blackmarket_Inspect_C_OnGainedStackFocused::PreviousValue' has a wrong offset!");

// Function WBP_UI_Blackmarket_Inspect.WBP_UI_Blackmarket_Inspect_C.CanInspectItem
// 0x00C0 (0x00C0 - 0x0000)
struct WBP_UI_Blackmarket_Inspect_C_CanInspectItem final
{
public:
	class USBZInventoryBaseData*                  InInspectData;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USBZGloveData*                          K2Node_DynamicCast_AsSBZGlove_Data;                // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	const class USBZSuitBaseData*                 K2Node_DynamicCast_AsSBZSuit_Base_Data;            // 0x0020(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	const class USBZMaskPreconfigData*            K2Node_DynamicCast_AsSBZMask_Preconfig_Data;       // 0x0030(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	const class USBZMaskVFXData*                  K2Node_DynamicCast_AsSBZMask_VFXData;              // 0x0040(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	const class USBZMaskMaterialData*             K2Node_DynamicCast_AsSBZMask_Material_Data;        // 0x0050(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	const class USBZMaskPatternData*              K2Node_DynamicCast_AsSBZMask_Pattern_Data;         // 0x0060(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_5;                     // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_69[0x7];                                       // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	const class USBZMaskMouldData*                K2Node_DynamicCast_AsSBZMask_Mould_Data;           // 0x0070(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_6;                     // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_79[0x7];                                       // 0x0079(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USBZMaskData*                           K2Node_DynamicCast_AsSBZMask_Data;                 // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_7;                     // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_89[0x7];                                       // 0x0089(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USBZWeaponPresetConfigData*             K2Node_DynamicCast_AsSBZWeapon_Preset_Config_Data; // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_8;                     // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_99[0x7];                                       // 0x0099(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	const class USBZWeaponCharmData*              K2Node_DynamicCast_AsSBZWeapon_Charm_Data;         // 0x00A0(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_9;                     // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A9[0x7];                                       // 0x00A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USBZBaseWeaponData*                     K2Node_DynamicCast_AsSBZBase_Weapon_Data;          // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_10;                    // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_UI_Blackmarket_Inspect_C_CanInspectItem) == 0x000008, "Wrong alignment on WBP_UI_Blackmarket_Inspect_C_CanInspectItem");
static_assert(sizeof(WBP_UI_Blackmarket_Inspect_C_CanInspectItem) == 0x0000C0, "Wrong size on WBP_UI_Blackmarket_Inspect_C_CanInspectItem");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_CanInspectItem, InInspectData) == 0x000000, "Member 'WBP_UI_Blackmarket_Inspect_C_CanInspectItem::InInspectData' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_CanInspectItem, ReturnValue) == 0x000008, "Member 'WBP_UI_Blackmarket_Inspect_C_CanInspectItem::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_CanInspectItem, K2Node_DynamicCast_AsSBZGlove_Data) == 0x000010, "Member 'WBP_UI_Blackmarket_Inspect_C_CanInspectItem::K2Node_DynamicCast_AsSBZGlove_Data' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_CanInspectItem, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'WBP_UI_Blackmarket_Inspect_C_CanInspectItem::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_CanInspectItem, K2Node_DynamicCast_AsSBZSuit_Base_Data) == 0x000020, "Member 'WBP_UI_Blackmarket_Inspect_C_CanInspectItem::K2Node_DynamicCast_AsSBZSuit_Base_Data' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_CanInspectItem, K2Node_DynamicCast_bSuccess_1) == 0x000028, "Member 'WBP_UI_Blackmarket_Inspect_C_CanInspectItem::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_CanInspectItem, K2Node_DynamicCast_AsSBZMask_Preconfig_Data) == 0x000030, "Member 'WBP_UI_Blackmarket_Inspect_C_CanInspectItem::K2Node_DynamicCast_AsSBZMask_Preconfig_Data' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_CanInspectItem, K2Node_DynamicCast_bSuccess_2) == 0x000038, "Member 'WBP_UI_Blackmarket_Inspect_C_CanInspectItem::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_CanInspectItem, K2Node_DynamicCast_AsSBZMask_VFXData) == 0x000040, "Member 'WBP_UI_Blackmarket_Inspect_C_CanInspectItem::K2Node_DynamicCast_AsSBZMask_VFXData' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_CanInspectItem, K2Node_DynamicCast_bSuccess_3) == 0x000048, "Member 'WBP_UI_Blackmarket_Inspect_C_CanInspectItem::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_CanInspectItem, K2Node_DynamicCast_AsSBZMask_Material_Data) == 0x000050, "Member 'WBP_UI_Blackmarket_Inspect_C_CanInspectItem::K2Node_DynamicCast_AsSBZMask_Material_Data' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_CanInspectItem, K2Node_DynamicCast_bSuccess_4) == 0x000058, "Member 'WBP_UI_Blackmarket_Inspect_C_CanInspectItem::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_CanInspectItem, K2Node_DynamicCast_AsSBZMask_Pattern_Data) == 0x000060, "Member 'WBP_UI_Blackmarket_Inspect_C_CanInspectItem::K2Node_DynamicCast_AsSBZMask_Pattern_Data' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_CanInspectItem, K2Node_DynamicCast_bSuccess_5) == 0x000068, "Member 'WBP_UI_Blackmarket_Inspect_C_CanInspectItem::K2Node_DynamicCast_bSuccess_5' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_CanInspectItem, K2Node_DynamicCast_AsSBZMask_Mould_Data) == 0x000070, "Member 'WBP_UI_Blackmarket_Inspect_C_CanInspectItem::K2Node_DynamicCast_AsSBZMask_Mould_Data' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_CanInspectItem, K2Node_DynamicCast_bSuccess_6) == 0x000078, "Member 'WBP_UI_Blackmarket_Inspect_C_CanInspectItem::K2Node_DynamicCast_bSuccess_6' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_CanInspectItem, K2Node_DynamicCast_AsSBZMask_Data) == 0x000080, "Member 'WBP_UI_Blackmarket_Inspect_C_CanInspectItem::K2Node_DynamicCast_AsSBZMask_Data' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_CanInspectItem, K2Node_DynamicCast_bSuccess_7) == 0x000088, "Member 'WBP_UI_Blackmarket_Inspect_C_CanInspectItem::K2Node_DynamicCast_bSuccess_7' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_CanInspectItem, K2Node_DynamicCast_AsSBZWeapon_Preset_Config_Data) == 0x000090, "Member 'WBP_UI_Blackmarket_Inspect_C_CanInspectItem::K2Node_DynamicCast_AsSBZWeapon_Preset_Config_Data' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_CanInspectItem, K2Node_DynamicCast_bSuccess_8) == 0x000098, "Member 'WBP_UI_Blackmarket_Inspect_C_CanInspectItem::K2Node_DynamicCast_bSuccess_8' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_CanInspectItem, K2Node_DynamicCast_AsSBZWeapon_Charm_Data) == 0x0000A0, "Member 'WBP_UI_Blackmarket_Inspect_C_CanInspectItem::K2Node_DynamicCast_AsSBZWeapon_Charm_Data' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_CanInspectItem, K2Node_DynamicCast_bSuccess_9) == 0x0000A8, "Member 'WBP_UI_Blackmarket_Inspect_C_CanInspectItem::K2Node_DynamicCast_bSuccess_9' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_CanInspectItem, K2Node_DynamicCast_AsSBZBase_Weapon_Data) == 0x0000B0, "Member 'WBP_UI_Blackmarket_Inspect_C_CanInspectItem::K2Node_DynamicCast_AsSBZBase_Weapon_Data' has a wrong offset!");
static_assert(offsetof(WBP_UI_Blackmarket_Inspect_C_CanInspectItem, K2Node_DynamicCast_bSuccess_10) == 0x0000B8, "Member 'WBP_UI_Blackmarket_Inspect_C_CanInspectItem::K2Node_DynamicCast_bSuccess_10' has a wrong offset!");

}

