#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_Widget_CombinedHealthArmourBar

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_UI_Widget_CombinedHealthArmourBar.WBP_UI_Widget_CombinedHealthArmourBar_C
// 0x0010 (0x02D0 - 0x02C0)
class UWBP_UI_Widget_CombinedHealthArmourBar_C final : public UPD3HUDPlayerCombinedHealthWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_UI_Widget_SegmentedAttributeBar_C* ArmorWidget;                                       // 0x02C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_UI_Widget_CombinedHealthArmourBar(int32 EntryPoint);
	void BP_OnReplenishArmorChanged(bool bIsReplenishingArmor);
	void Setup();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_UI_Widget_CombinedHealthArmourBar_C">();
	}
	static class UWBP_UI_Widget_CombinedHealthArmourBar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_UI_Widget_CombinedHealthArmourBar_C>();
	}
};
static_assert(alignof(UWBP_UI_Widget_CombinedHealthArmourBar_C) == 0x000008, "Wrong alignment on UWBP_UI_Widget_CombinedHealthArmourBar_C");
static_assert(sizeof(UWBP_UI_Widget_CombinedHealthArmourBar_C) == 0x0002D0, "Wrong size on UWBP_UI_Widget_CombinedHealthArmourBar_C");
static_assert(offsetof(UWBP_UI_Widget_CombinedHealthArmourBar_C, UberGraphFrame) == 0x0002C0, "Member 'UWBP_UI_Widget_CombinedHealthArmourBar_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_UI_Widget_CombinedHealthArmourBar_C, ArmorWidget) == 0x0002C8, "Member 'UWBP_UI_Widget_CombinedHealthArmourBar_C::ArmorWidget' has a wrong offset!");

}

