#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_LoginSceen_InfoPopUp

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_UI_LoginSceen_InfoPopUp.WBP_UI_LoginSceen_InfoPopUp_C.ExecuteUbergraph_WBP_UI_LoginSceen_InfoPopUp
// 0x0004 (0x0004 - 0x0000)
struct WBP_UI_LoginSceen_InfoPopUp_C_ExecuteUbergraph_WBP_UI_LoginSceen_InfoPopUp final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_UI_LoginSceen_InfoPopUp_C_ExecuteUbergraph_WBP_UI_LoginSceen_InfoPopUp) == 0x000004, "Wrong alignment on WBP_UI_LoginSceen_InfoPopUp_C_ExecuteUbergraph_WBP_UI_LoginSceen_InfoPopUp");
static_assert(sizeof(WBP_UI_LoginSceen_InfoPopUp_C_ExecuteUbergraph_WBP_UI_LoginSceen_InfoPopUp) == 0x000004, "Wrong size on WBP_UI_LoginSceen_InfoPopUp_C_ExecuteUbergraph_WBP_UI_LoginSceen_InfoPopUp");
static_assert(offsetof(WBP_UI_LoginSceen_InfoPopUp_C_ExecuteUbergraph_WBP_UI_LoginSceen_InfoPopUp, EntryPoint) == 0x000000, "Member 'WBP_UI_LoginSceen_InfoPopUp_C_ExecuteUbergraph_WBP_UI_LoginSceen_InfoPopUp::EntryPoint' has a wrong offset!");

}

