#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_WixiaComputer

#include "Basic.hpp"

#include "WBP_WixiaComputer_classes.hpp"
#include "WBP_WixiaComputer_parameters.hpp"


namespace SDK
{

// Function WBP_WixiaComputer.WBP_WixiaComputer_C.ExecuteUbergraph_WBP_WixiaComputer
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_WixiaComputer_C::ExecuteUbergraph_WBP_WixiaComputer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WixiaComputer_C", "ExecuteUbergraph_WBP_WixiaComputer");

	Params::WBP_WixiaComputer_C_ExecuteUbergraph_WBP_WixiaComputer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_WixiaComputer.WBP_WixiaComputer_C.updateInformation
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Main                                                   (BlueprintVisible, BlueprintReadOnly, Parm)
// class FText                             Secondary                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm)
// class FText                             Additional                                             (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_WixiaComputer_C::UpdateInformation(const class FText& Main, const class FText& Secondary, const class FText& Additional)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WixiaComputer_C", "updateInformation");

	Params::WBP_WixiaComputer_C_UpdateInformation Parms{};

	Parms.Main = std::move(Main);
	Parms.Secondary = std::move(Secondary);
	Parms.Additional = std::move(Additional);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_WixiaComputer.WBP_WixiaComputer_C.updateKeypadPossibleCodes
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<int32>                           Codes                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_WixiaComputer_C::UpdateKeypadPossibleCodes(const TArray<int32>& Codes)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WixiaComputer_C", "updateKeypadPossibleCodes");

	Params::WBP_WixiaComputer_C_UpdateKeypadPossibleCodes Parms{};

	Parms.Codes = std::move(Codes);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_WixiaComputer.WBP_WixiaComputer_C.updateHackingProgress
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Progress                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_WixiaComputer_C::UpdateHackingProgress(int32 Progress)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WixiaComputer_C", "updateHackingProgress");

	Params::WBP_WixiaComputer_C_UpdateHackingProgress Parms{};

	Parms.Progress = Progress;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_WixiaComputer.WBP_WixiaComputer_C.updateHackingTimerProcessName
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             InText                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_WixiaComputer_C::UpdateHackingTimerProcessName(const class FText& InText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WixiaComputer_C", "updateHackingTimerProcessName");

	Params::WBP_WixiaComputer_C_UpdateHackingTimerProcessName Parms{};

	Parms.InText = std::move(InText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_WixiaComputer.WBP_WixiaComputer_C.UpdateUnlockDisplayText
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FSBZHackableDisplayText          NewDisplayText                                         (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_WixiaComputer_C::UpdateUnlockDisplayText(const struct FSBZHackableDisplayText& NewDisplayText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WixiaComputer_C", "UpdateUnlockDisplayText");

	Params::WBP_WixiaComputer_C_UpdateUnlockDisplayText Parms{};

	Parms.NewDisplayText = std::move(NewDisplayText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_WixiaComputer.WBP_WixiaComputer_C.UpdateSuccessText
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             InText                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_WixiaComputer_C::UpdateSuccessText(const class FText& InText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WixiaComputer_C", "UpdateSuccessText");

	Params::WBP_WixiaComputer_C_UpdateSuccessText Parms{};

	Parms.InText = std::move(InText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_WixiaComputer.WBP_WixiaComputer_C.UpdateEmailDisplayText
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FSBZHackableDisplayText          DisplayText                                            (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_WixiaComputer_C::UpdateEmailDisplayText(const struct FSBZHackableDisplayText& DisplayText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WixiaComputer_C", "UpdateEmailDisplayText");

	Params::WBP_WixiaComputer_C_UpdateEmailDisplayText Parms{};

	Parms.DisplayText = std::move(DisplayText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_WixiaComputer.WBP_WixiaComputer_C.Code
// (BlueprintCallable, BlueprintEvent)

void UWBP_WixiaComputer_C::Code()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WixiaComputer_C", "Code");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_WixiaComputer.WBP_WixiaComputer_C.Names
// (BlueprintCallable, BlueprintEvent)

void UWBP_WixiaComputer_C::Names()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WixiaComputer_C", "Names");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_WixiaComputer.WBP_WixiaComputer_C.Email
// (BlueprintCallable, BlueprintEvent)

void UWBP_WixiaComputer_C::Email()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WixiaComputer_C", "Email");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_WixiaComputer.WBP_WixiaComputer_C.Unlocked
// (BlueprintCallable, BlueprintEvent)

void UWBP_WixiaComputer_C::Unlocked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WixiaComputer_C", "Unlocked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_WixiaComputer.WBP_WixiaComputer_C.NotActive
// (BlueprintCallable, BlueprintEvent)

void UWBP_WixiaComputer_C::NotActive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WixiaComputer_C", "NotActive");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_WixiaComputer.WBP_WixiaComputer_C.Active
// (BlueprintCallable, BlueprintEvent)

void UWBP_WixiaComputer_C::Active()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WixiaComputer_C", "Active");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_WixiaComputer.WBP_WixiaComputer_C.Done
// (BlueprintCallable, BlueprintEvent)

void UWBP_WixiaComputer_C::Done()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WixiaComputer_C", "Done");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_WixiaComputer.WBP_WixiaComputer_C.Interupted
// (BlueprintCallable, BlueprintEvent)

void UWBP_WixiaComputer_C::Interupted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WixiaComputer_C", "Interupted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_WixiaComputer.WBP_WixiaComputer_C.Progressing
// (BlueprintCallable, BlueprintEvent)

void UWBP_WixiaComputer_C::Progressing()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WixiaComputer_C", "Progressing");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_WixiaComputer.WBP_WixiaComputer_C.Failed
// (BlueprintCallable, BlueprintEvent)

void UWBP_WixiaComputer_C::Failed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WixiaComputer_C", "Failed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_WixiaComputer.WBP_WixiaComputer_C.HideAllWidgetsButOne
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          WidgetToShow                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_WixiaComputer_C::HideAllWidgetsButOne(class UWidget* WidgetToShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WixiaComputer_C", "HideAllWidgetsButOne");

	Params::WBP_WixiaComputer_C_HideAllWidgetsButOne Parms{};

	Parms.WidgetToShow = WidgetToShow;

	UObject::ProcessEvent(Func, &Parms);
}

}

