#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_SM_ActionPhaseTransition

#include "Basic.hpp"

#include "WBP_UI_SM_ActionPhaseTransition_classes.hpp"
#include "WBP_UI_SM_ActionPhaseTransition_parameters.hpp"


namespace SDK
{

// Function WBP_UI_SM_ActionPhaseTransition.WBP_UI_SM_ActionPhaseTransition_C.ExecuteUbergraph_WBP_UI_SM_ActionPhaseTransition
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_SM_ActionPhaseTransition_C::ExecuteUbergraph_WBP_UI_SM_ActionPhaseTransition(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_SM_ActionPhaseTransition_C", "ExecuteUbergraph_WBP_UI_SM_ActionPhaseTransition");

	Params::WBP_UI_SM_ActionPhaseTransition_C_ExecuteUbergraph_WBP_UI_SM_ActionPhaseTransition Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_SM_ActionPhaseTransition.WBP_UI_SM_ActionPhaseTransition_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_UI_SM_ActionPhaseTransition_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_SM_ActionPhaseTransition_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_SM_ActionPhaseTransition.WBP_UI_SM_ActionPhaseTransition_C.WidgetAnimationEvt_FadeIn_K2Node_WidgetAnimationEvent_1
// (BlueprintEvent)

void UWBP_UI_SM_ActionPhaseTransition_C::WidgetAnimationEvt_FadeIn_K2Node_WidgetAnimationEvent_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_SM_ActionPhaseTransition_C", "WidgetAnimationEvt_FadeIn_K2Node_WidgetAnimationEvent_1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_SM_ActionPhaseTransition.WBP_UI_SM_ActionPhaseTransition_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_UI_SM_ActionPhaseTransition_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_SM_ActionPhaseTransition_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_SM_ActionPhaseTransition.WBP_UI_SM_ActionPhaseTransition_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_UI_SM_ActionPhaseTransition_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_SM_ActionPhaseTransition_C", "PreConstruct");

	Params::WBP_UI_SM_ActionPhaseTransition_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_SM_ActionPhaseTransition.WBP_UI_SM_ActionPhaseTransition_C.WidgetAnimationEvt_LevelDataFadeIn_K2Node_WidgetAnimationEvent_0
// (BlueprintEvent)

void UWBP_UI_SM_ActionPhaseTransition_C::WidgetAnimationEvt_LevelDataFadeIn_K2Node_WidgetAnimationEvent_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_SM_ActionPhaseTransition_C", "WidgetAnimationEvt_LevelDataFadeIn_K2Node_WidgetAnimationEvent_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_SM_ActionPhaseTransition.WBP_UI_SM_ActionPhaseTransition_C.OnAnimationComplete
// (BlueprintCallable, BlueprintEvent)

void UWBP_UI_SM_ActionPhaseTransition_C::OnAnimationComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_SM_ActionPhaseTransition_C", "OnAnimationComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UI_SM_ActionPhaseTransition.WBP_UI_SM_ActionPhaseTransition_C.DisplayTransition
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_UI_SM_ActionPhaseTransition_C::DisplayTransition()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_SM_ActionPhaseTransition_C", "DisplayTransition");

	UObject::ProcessEvent(Func, nullptr);
}

}

